name: Packer Template Validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    name: Validate Packer Template
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run packer fmt check
        id: fmt
        working-directory: ./packer
        run: |
          packer fmt -check cloud.pkr.hcl
        continue-on-error: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create application zip for validation
        run: |
          zip -r webapp.zip . -x "*.git*" "packer/*" ".github/*" "systemd/*" "venv/*"

      - name: Run packer validate
        id: validate
        working-directory: ./packer
        run: |
          packer init .
          packer validate -var 'postgres_password=dummy_password' cloud.pkr.hcl
        continue-on-error: false
